Feature/witi 217 create custom fields entity on cost centre md table
syatt-io/b2b-organizations pull request #2
Opened 2022-08-15 19:02 UTC by RamanSel

#### What problem is this solving?

Adding custom fields to organizations. [WITI-217](https://syatt.atlassian.net/browse/WITI-217).

#### How to test it?

[Workspace](https://witi217--whitebird.myvtex.com/admin/b2b-organizations/organizations/#/settings)

#### Screenshots or example usage:

![witi217--whitebird myvtex com_admin_b2b-organizations_organizations_ (1)](https://user-images.githubusercontent.com/44775362/184696497-693e8761-8fa4-46d5-8306-fcabec421e9e.png)

#### Related to / Depends on

Depends on [b2b-organizations-graphql part](url).

2022-08-15 21:06 UTC, jonmast requested changes

2022-08-23 20:10 UTC, RamanSel commented on react/admin/AutoApproveSettings.tsx
> -import React, { useEffect, useState, useContext } from 'react'
✅ moved component to a separate file and route

2022-08-23 20:16 UTC, RamanSel commented on react/admin/AutoApproveSettings.tsx
> +  type: string
✅ Added type: 'text' for FE and BE

2022-08-23 20:17 UTC, RamanSel commented on react/admin/OrganizationCustomFields.tsx
> +  const [customField, setCustomField] = useState<CustomField>({
✅ state now lives inside 'OrganizationCustomFields' component

2022-08-30 14:56 UTC, RamanSel commented
@jonmast, 
I've prettified the code a bit by using their other files as an example, please advice if it's good enough to submit a PR.

2022-08-30 15:36 UTC, jonmast commented on react/admin/OrganizationCustomFields.tsx
> +  const [customField, setCustomField] = useState<CustomField>({
I'm still seeing a state variable in the field component here: https://github.com/syatt-io/b2b-organizations/pull/2/files#diff-e867d185ea29743c679c5578bc3d1ec02be6aa5f97b264114b3b9b8c687ede14R24

2022-08-30 15:38 UTC, jonmast commented
@RamanSel You'll want to make sure `yarn lint` isn't returning any errors before submitting, that would cause CI to fail

2022-09-06 16:03 UTC, jonmast requested changes
I'm still seeing the state issue, feel free to ping me if it doesn't make sense and we can discuss further.

2022-09-08 13:19 UTC, RamanSel commented
New PR will be submitted that includes logic for saving custom fields input values

2022-09-08 13:19 UTC, closed without merging